<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <AssemblyName>GroceryPos.Printing</AssemblyName>
    <RootNamespace>GroceryPos.Printing</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\GroceryPos.Domain\GroceryPos.Domain.csproj" />
  </ItemGroup>
</Project>
